//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accesibilitiLabs.Models.domainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class queries
    {
        public int idQueri { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string queri { get; set; }
        public string title { get; set; }
    }
}
